### ISSUE TITLE
not compatible with redmine_track_control and redmine accept

### ISSUE THREAD

**Issue by archonwang** [akiko-pusu/redmine_issue_templates#21]
it seems not compatible with the redmine_track_control, please check it.
redmine_track_control
> https://github.com/fishermans/redmine_track_control.git

error log

```
An ActionView::Template::Error occurred in issues#new:
 
  undefined method `id' for nil:NilClass
  plugins/redmine_issue_templates/app/views/issue_templates/_issue_select_form.html.erb:34:in `_plugins_redmine_issue_templates_app_views_issue_templates__issue_select_form_html_erb___2990508753618961756_23207420'
 
 
-------------------------------
Request:
-------------------------------
 
* URL : http://192.168.1.41/projects/web/issues/new
  * HTTP Method: GET
  * IP address : 192.168.60.239
  * Parameters : {"controller"=>"issues", "action"=>"new", "project_id"=>"web"}
  * Timestamp  : 2016-06-15 12:34:14 UTC
  * Server : jira
  * Rails root : /opt/redmine
  * Process: 12008
 
-------------------------------
Session:
-------------------------------
 
  * session id: "0941212de1a94ec9b9fd3df0238dbe95"
  * data: {"session_id"=>"0941212de1a94ec9b9fd3df0238dbe95",
   "user_id"=>80,
   "tk"=>"dcaf6e0369082e16232a3df700ab12698df6e3fa",
   "sudo_timestamp"=>1465994047,
   "my_page_sort"=>"none",
   "_csrf_token"=>"b27045Op97N31rH29Fp1Cc4N7gy5P2D2cwN2xKpjVTc=",
   "recent_projects"=>[11]}
 
-------------------------------
Environment:
-------------------------------
 
  * GATEWAY_INTERFACE                              : CGI/1.2
  * HTTP_ACCEPT                                    : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  * HTTP_ACCEPT_ENCODING                           : gzip, deflate, sdch
  * HTTP_ACCEPT_LANGUAGE                           : zh-CN,zh;q=0.8
  * HTTP_CONNECTION                                : keep-alive
  * HTTP_COOKIE                                    : _redmine_session=Qm5PZUY0NzEwc0hWN0lRQnFJdnNiOE5paWtjTC9UNUxIQTRBZTF4ODlPTzcyOGR0b05UTUpGd0tWZFNNN1A3Unh3QnNGNVZCRVBNbWZLbklrZnNocnFGUkg5Qm5QL1RJT0g5Nnk0WC9wZTEza1YrT2RzQUlWSFMvOTIwOUpJdFpJMWVLbmhEYkNnVUpBY3pVa1djYmZYUTRML2s0NXdrbjJMM0dzVGZkak5pTmRIS3lxeUl3TDhobWN5RVRsYXYrcnlKbTRqTzRLMWVUS0hGcFA0Q0NRYkpJbGhPdHNKbHhiVDJ4V0JCdEE3Sk1ibjVVc2pQODExbmJUeU9zaHBjZHdtSnd5SzFKTFJmU1gzZXdpOTFNUmQ5ZUQxTHAwVlc2SHBJdFZqeThzT1dkL3djY01JTmxGdlhwK2JFay93YTBhM3didFpKcmp6T1V1N1RMaEh2TVhLZExMcXF3amlBblpVdDQzQmxDSWM4cGRzNnVDUkF1Mk1MNGJCTXFyK0Y4LS1OZ3VKK2tOeEh1bUZUVDV6WUtGZmlBPT0%3D--d5c745fa1d322f506c4e7949afbaf68886c4f339
  * HTTP_HOST                                      : 192.168.1.41
  * HTTP_IF_NONE_MATCH                             : W/"4d8c6a4027a57d2aee7d257fea1ee57a"
* HTTP_REFERER : http://192.168.1.41/projects/web?jump=my
  * HTTP_UPGRADE_INSECURE_REQUESTS                 : 1
  * HTTP_USER_AGENT                                : Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
  * HTTP_VERSION                                   : HTTP/1.1
  * ORIGINAL_FULLPATH                              : /projects/web/issues/new
  * ORIGINAL_SCRIPT_NAME                           :
  * PATH_INFO                                      : /projects/web/issues/new
  * QUERY_STRING                                   :
  * REMOTE_ADDR                                    : 192.168.60.239
  * REQUEST_METHOD                                 : GET
  * REQUEST_PATH                                   : /projects/web/issues/new
  * REQUEST_URI                                    : /projects/web/issues/new
  * ROUTES_50047920_SCRIPT_NAME                    :
  * SCRIPT_NAME                                    :
  * SERVER_NAME                                    : 192.168.1.41
  * SERVER_PORT                                    : 80
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : thin 1.7.0 codename Dunder Mifflin
  * action_controller.instance                     : #<IssuesController:0x00000005b8e5c0>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x00000005451550>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x00000005bc3798>
  * action_dispatch.cookies_digest                 :
  * action_dispatch.cookies_serializer             :
  * action_dispatch.encrypted_cookie_salt          : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
  * action_dispatch.http_auth_salt                 : http authentication
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x000000060bbc50>
  * action_dispatch.logger                         : #<Logger:0x00000006154c48>
  * action_dispatch.parameter_filter               : [:password]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 192.168.60.239
  * action_dispatch.request.content_type           :
  * action_dispatch.request.formats                : [#<Mime::Type:0x00000002bd3bf0 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=-581062547691683792>]
  * action_dispatch.request.parameters             : {"controller"=>"issues", "action"=>"new", "project_id"=>"web"}
  * action_dispatch.request.path_parameters        : {:controller=>"issues", :action=>"new", :project_id=>"web"}
  * action_dispatch.request.query_parameters       : {}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"0941212de1a94ec9b9fd3df0238dbe95", "user_id"=>80, "tk"=>"dcaf6e0369082e16232a3df700ab12698df6e3fa", "sudo_timestamp"=>1465994047, "my_page_sort"=>"none", "_csrf_token"=>"b27045Op97N31rH29Fp1Cc4N7gy5P2D2cwN2xKpjVTc=", "recent_projects"=>[11]}
  * action_dispatch.request_id                     : 6464193d-83a5-4856-97f5-9c045047ce73
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x00000005f75760>
  * action_dispatch.secret_key_base                : 0766de1a38458f6ed259d92d32f935a6d1ca6679e6bf4ee258716df9e83186497557be97146359d2
  * action_dispatch.secret_token                   :
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : signed cookie
  * async.callback                                 : #<Method: Thin::Connection#post_process>
  * async.close                                    : #<EventMachine::DefaultDeferrable:0x00000005b37720>
  * rack.errors                                    : #<IO:0x00000001bdd598>
  * rack.input                                     : #<StringIO:0x00000005b058b0>
  * rack.multiprocess                              : false
  * rack.multithread                               : true
  * rack.request.cookie_hash                       : {"_redmine_session"=>"Qm5PZUY0NzEwc0hWN0lRQnFJdnNiOE5paWtjTC9UNUxIQTRBZTF4ODlPTzcyOGR0b05UTUpGd0tWZFNNN1A3Unh3QnNGNVZCRVBNbWZLbklrZnNocnFGUkg5Qm5QL1RJT0g5Nnk0WC9wZTEza1YrT2RzQUlWSFMvOTIwOUpJdFpJMWVLbmhEYkNnVUpBY3pVa1djYmZYUTRML2s0NXdrbjJMM0dzVGZkak5pTmRIS3lxeUl3TDhobWN5RVRsYXYrcnlKbTRqTzRLMWVUS0hGcFA0Q0NRYkpJbGhPdHNKbHhiVDJ4V0JCdEE3Sk1ibjVVc2pQODExbmJUeU9zaHBjZHdtSnd5SzFKTFJmU1gzZXdpOTFNUmQ5ZUQxTHAwVlc2SHBJdFZqeThzT1dkL3djY01JTmxGdlhwK2JFay93YTBhM3didFpKcmp6T1V1N1RMaEh2TVhLZExMcXF3amlBblpVdDQzQmxDSWM4cGRzNnVDUkF1Mk1MNGJCTXFyK0Y4LS1OZ3VKK2tOeEh1bUZUVDV6WUtGZmlBPT0=--d5c745fa1d322f506c4e7949afbaf68886c4f339"}
  * rack.request.cookie_string                     : _redmine_session=Qm5PZUY0NzEwc0hWN0lRQnFJdnNiOE5paWtjTC9UNUxIQTRBZTF4ODlPTzcyOGR0b05UTUpGd0tWZFNNN1A3Unh3QnNGNVZCRVBNbWZLbklrZnNocnFGUkg5Qm5QL1RJT0g5Nnk0WC9wZTEza1YrT2RzQUlWSFMvOTIwOUpJdFpJMWVLbmhEYkNnVUpBY3pVa1djYmZYUTRML2s0NXdrbjJMM0dzVGZkak5pTmRIS3lxeUl3TDhobWN5RVRsYXYrcnlKbTRqTzRLMWVUS0hGcFA0Q0NRYkpJbGhPdHNKbHhiVDJ4V0JCdEE3Sk1ibjVVc2pQODExbmJUeU9zaHBjZHdtSnd5SzFKTFJmU1gzZXdpOTFNUmQ5ZUQxTHAwVlc2SHBJdFZqeThzT1dkL3djY01JTmxGdlhwK2JFay93YTBhM3didFpKcmp6T1V1N1RMaEh2TVhLZExMcXF3amlBblpVdDQzQmxDSWM4cGRzNnVDUkF1Mk1MNGJCTXFyK0Y4LS1OZ3VKK2tOeEh1bUZUVDV6WUtGZmlBPT0%3D--d5c745fa1d322f506c4e7949afbaf68886c4f339
  * rack.request.query_hash                        : {}
  * rack.request.query_string                      :
  * rack.run_once                                  : false
  * rack.session                                   : #<ActionDispatch::Request::Session:0x00000005b637d0>
  * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x00000005b63550>
  * rack.url_scheme                                : http
  * rack.version                                   : [1, 0]
 
-------------------------------
Backtrace:
-------------------------------
 
  plugins/redmine_issue_templates/app/views/issue_templates/_issue_select_form.html.erb:34:in `_plugins_redmine_issue_templates_app_views_issue_templates__issue_select_form_html_erb___2990508753618961756_23207420'
  plugins/redmine_issue_templates/lib/issue_templates_issues_hook.rb:27:in `view_issues_form_details_top'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/issues/_form.html.erb:2:in `block in _app_views_issues__form_html_erb___3961347763519880095_37991140'
  app/helpers/application_helper.rb:1038:in `labelled_fields_for'
  app/views/issues/_form.html.erb:1:in `_app_views_issues__form_html_erb___3961347763519880095_37991140'
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
  app/views/issues/new.html.erb:11:in `block in _app_views_issues_new_html_erb___4442599922157199054_40004600'
  app/helpers/application_helper.rb:1031:in `labelled_form_for'
  app/views/issues/new.html.erb:5:in `_app_views_issues_new_html_erb___4442599922157199054_40004600'
  app/controllers/issues_controller.rb:130:in `block (2 levels) in new'
  app/controllers/issues_controller.rb:129:in `new'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
 
```

**Comment by archonwang** [comment]
@akiko-pusu 
Please check it, when  I open the new issue page, it occurred . Thanks so much.

**Comment by archonwang** [comment]
@akiko-pusu 
I reproduce the bug use these steps
1. login and config the roles and rights.
2. config the Tracker permissions, unchecked the Create defect
3. config the issue type: defect with some issue template
4. user only with this role would occur the error ,if you check the Create defect again, the error would disappear.  It's strange for I think someone that wouldn't use the defect type .

**Comment by akiko-pusu** [comment]
Hi, @archonwang 
Sorry I don’t know much about redmine_track_control plugin.
And please tell me which version you use, Redmine, issue_template plugin, redmine_track_control plugin.

I would also try them with my latest (development) code.

**Comment by archonwang** [comment]
@akiko-pusu , Thanks for your help.

my Redmine environment with the redmine_issue_template
```
Environment:
  Redmine version                3.2.3.stable.15529
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               Mysql2
```
 the plugin redmine_tracker_control
https://github.com/fishermans/redmine_track_control   branch master

the plugin redime_issue_template with master and latest version.

the issue would happen in some special condition, if you have any question about reproducinig it, please let me know. Thanks.

**Comment by akiko-pusu** [comment]
This is because redmine_track_control plugin remove the variable through t’s plugin’s patch, such as @issue,  that Redmine’s original IssueController passed. 
( Ref. IssuesControllerPatch#check_tracker_id_with_trackcontrol )

Sorry I can’t have much time to support in this case, some trouble with other plugin, but if you hope to fix it, please try:

IssueTemplatesIssuesHook#view_issues_form_details_top

```
  def view_issues_form_details_top(context = {})
    action = context[:request].parameters[:action]
    project = context[:project]
    issue = context[:issue]
    return if issue.tracker_id.blank?      # add this line.
    setting = IssueTemplateSetting.find_or_create(project.id)
    copy_from = context[:request].parameters[:copy_from]
    is_triggered_by_status = triggered_by_status?(context[:request])
    return '' unless copy_from.blank?
    return '' unless (action == 'new' || action == 'update_form' || action == 'create') && !project.id.blank? && issue.id.blank?
    context[:controller].send(
      :render_to_string,
      partial: 'issue_templates/issue_select_form',
      locals: { setting: setting, issue: issue, is_triggered_by_status: is_triggered_by_status }
    )
  end
```  

After this modification, issue create form will be shown.
And tracker is not selected. When operator select tracker, request to update form field send and template pulldown is also generated.

**Comment by archonwang** [comment]
@akiko-pusu , 
Thanks so much. 
I will test it later.

**Comment by archonwang** [comment]
@akiko-pusu , it seems fixed the issue, but for another plugin, another question occured.

the problem is 404  for I have installed the plugin redmine accept (https://github.com/stefanzugal/accept-plugin.git)
`Page not found

The page you were trying to access doesn't exist or has been removed.`


error log is 
```

F, [2016-06-17T15:23:28.253832 #26762] FATAL -- : 
ActiveRecord::RecordNotFound (Couldn't find IssueStatus with 'id'=):
  plugins/accept/app/helpers/accept_helper.rb:7:in `generate_accept_button'
  plugins/accept/lib/hooks.rb:8:in `view_issues_form_details_bottom'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/issues/_form.html.erb:45:in `block in _app_views_issues__form_html_erb___2604903121743444123_44437480'
  app/helpers/application_helper.rb:1038:in `labelled_fields_for'
  app/views/issues/_form.html.erb:1:in `_app_views_issues__form_html_erb___2604903121743444123_44437480'
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
  app/views/issues/new.html.erb:11:in `block in _app_views_issues_new_html_erb__1849303014949587790_70206958061740'
  app/helpers/application_helper.rb:1031:in `labelled_form_for'
  app/views/issues/new.html.erb:5:in `_app_views_issues_new_html_erb__1849303014949587790_70206958061740'
  app/controllers/issues_controller.rb:130:in `block (2 levels) in new'
  app/controllers/issues_controller.rb:129:in `new'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

**Comment by akiko-pusu** [comment]
@archonwang 
This error is not due to my plugin.
As I wrote above comment, it’s due to redmine_track_control plugin remove the variable through t’s plugin’s patch, such as @issue, that Redmine’s original IssueController passed. 

And accept plugin tries to generate button to accept related @issue variable which should be passed by Redmine’s original IssueController. But redmine_track_control plugin remove the variable if the default tracker of the project is disable for operator.

I think if you want to prevent this error, you should change project’s default tracker into the one which every project member can create.

**Comment by archonwang** [comment]
@akiko-pusu , Thanks for your reply, I will try it later. 
at present, I will close the issue. if there's any question I will inform you ASAP. 

Thanks so much.

**Comment by akiko-pusu** [comment]
@archonwang 
Your welcome. Please let know if you need any support.
And thank you very much for your continuous support :)
