### ISSUE TITLE
Internal Error for Demand

### ISSUE THREAD

**Issue by liberodark** [akiko-pusu/redmine_issue_templates#238]
## Summary
Hi have migrate my Redmine 3.x in 4.x but all plugins have been updated your plugin was update in 0.3.1.

## Description
But all work but have internal error have try to find the bug and have see is your plugin.
Have remove your plugin and all is work.

## Environment

- Redmine version 4.0.2
- Installed plugins easy_gantt, easy_mindmup, easy_wbs
- Ruby version 2.4 RVM
- OS Platform Centos 7.6
- Database (MySQL) and its version
- Rails Env Production

## Visual Proof / Screenshot
![image](https://user-images.githubusercontent.com/4238928/55708737-f3d9d400-59e6-11e9-993b-c01173f4b65b.png)
![image](https://user-images.githubusercontent.com/4238928/55708901-5b901f00-59e7-11e9-8fbc-8df555bd34f6.png)

# This is log for Internal Error
```
  Rendering projects/settings.html.erb within layouts/base
  Rendered projects/settings.html.erb within layouts/base (23.9ms)
Completed 500 Internal Server Error in 51ms (ActiveRecord: 9.8ms)
  
ActionView::Template::Error (uninitialized constant IssueTemplates::ProjectsHelperPatch::IssueTemplateSetting
Did you mean?  IssueTemplates):
    1: <h2><%=l(:label_settings)%></h2>
    2: 
    3: <%= render_tabs project_settings_tabs %>
    4: 
    5: <% html_title(l(:label_settings)) -%>
  
plugins/redmine_issue_templates-master/lib/issue_templates/projects_helper_patch.rb:7:in `project_settings_tabs'
app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb__1092138142490081196_63070400'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
Started GET "/projects/airbus-aneto-afdx/settings" for 127.0.0.1 at 2019-04-08 10:40:30 +0200
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"airbus-aneto-afdx"}
  Current user: liberodark (id=953)
  Rendering projects/settings.html.erb within layouts/base
  Rendered projects/settings.html.erb within layouts/base (24.5ms)
Completed 500 Internal Server Error in 47ms (ActiveRecord: 8.7ms)
  
ActionView::Template::Error (uninitialized constant IssueTemplates::ProjectsHelperPatch::IssueTemplateSetting
Did you mean?  IssueTemplates):
    1: <h2><%=l(:label_settings)%></h2>
    2: 
    3: <%= render_tabs project_settings_tabs %>
    4: 
    5: <% html_title(l(:label_settings)) -%>
  
plugins/redmine_issue_templates-master/lib/issue_templates/projects_helper_patch.rb:7:in `project_settings_tabs'
app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb__1092138142490081196_63070400'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

# This is log for 404
```
Started GET "/plugin_assets/redmine_issue_templates/stylesheets/issue_templates.css" for 127.0.0.1 at 2019-04-08 10:42:07 +0200
  
ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_issue_templates/stylesheets/issue_templates.css"):
  
actionpack (5.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.6) lib/rack/content_length.rb:15:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.2.2) lib/rails/engine.rb:524:in `call'
rack (2.0.6) lib/rack/handler/webrick.rb:86:in `service'
/home/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
/home/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
/home/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
Started GET "/plugin_assets/redmine_issue_templates/javascripts/issue_templates.js" for 127.0.0.1 at 2019-04-08 10:42:07 +0200
  
ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_issue_templates/javascripts/issue_templates.js"):
  
actionpack (5.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.6) lib/rack/content_length.rb:15:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.2.2) lib/rails/engine.rb:524:in `call'
rack (2.0.6) lib/rack/handler/webrick.rb:86:in `service'
/home/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
/home/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
/home/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
Started GET "/plugin_assets/redmine_issue_templates/stylesheets/issue_templates.css" for 127.0.0.1 at 2019-04-08 10:42:07 +0200
  
ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_issue_templates/stylesheets/issue_templates.css"):
  
actionpack (5.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.6) lib/rack/content_length.rb:15:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.2.2) lib/rails/engine.rb:524:in `call'
rack (2.0.6) lib/rack/handler/webrick.rb:86:in `service'
/home/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
/home/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
/home/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'

```

**Comment by akiko-pusu** [comment]
@liberodark 
Thanks for trying my plugin.
It seems template plugin’s directory name is wrong.

Error log says:

> plugins/redmine_issue_templates-master/lib/issue_templates/projects_helper_patch.rb:7:in `project_settings_tabs'
app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb__1092138142490081196_63070400’

And as I mentioned at README, 

> Please note that plugin's folder name should be "redmine_issue_templates". If changed, some migration task will be failed.

plugin’s folder name should be "redmine_issue_templates”.
Please try to rename is, like  “redmine_issue_templates-master” to “redmine_issue_templates".

See: https://github.com/akiko-pusu/redmine_issue_templates#plugin-installation

**Comment by akiko-pusu** [comment]
Also, please try to run migration task again.
If you see any trouble related to migration task and there is no template data, try to uninstall and re-install following this step:
- https://www.r-labs.org/projects/issue-template/wiki/About_en#Uninstall-plugin
- https://www.r-labs.org/projects/issue-template/wiki/About_en#Manual-uninstall

**Comment by akiko-pusu** [comment]
Related: https://www.redmine.org/issues/31110 (Redmine also raises error in case plugin's id and directory name are different.)

**Comment by liberodark** [comment]
Is ok have rename the folder of plugin
