### ISSUE TITLE
Cannot see Issue Templates when opening a new issue

### ISSUE THREAD

**Issue by olegblecher** [akiko-pusu/redmine_issue_templates#357]
#89  Summary

I have created a few templates on an issue. I have also allowed the user to create templates and view them. However, when I create a new issue, I do not see the templates. A screenshot is attached.

## Description
This is what I see in the logs:

```
ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_issue_templates/javascripts/issue_templates.js"):

actionpack (5.2.4.2) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.4.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.4.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.4.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.4.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.4.2) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.4.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.2) lib/rack/method_override.rb:24:in `call'
rack (2.2.2) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.4.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.2) lib/rack/content_length.rb:17:in `call'
rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
railties (5.2.4.2) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_issue_templates/stylesheets/issue_templates.css"):

actionpack (5.2.4.2) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.4.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.4.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.4.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.4.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.4.2) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.4.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.2) lib/rack/method_override.rb:24:in `call'
rack (2.2.2) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.4.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.2) lib/rack/content_length.rb:17:in `call'
rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
railties (5.2.4.2) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

## Environment
  Redmine version                4.0.6.stable
  Ruby version                   2.6.5-p114 (2019-10-01) [x86_64-linux]
  Rails version                  5.2.4.2
  Ubuntu 20.04

These informations are greatly helpful to support quickly.
You can get these informations from Redmine's information page.
(E.g. http://example.com/admin/info)

- Redmine version
- Installed plugins
- Ruby version
- OS Platform
- Database (MariaDB, MySQL, PostgreSQL) and its version
- Rails Env

## Visual Proof / Screenshot

When reporting an application error, post the error stack trace that 
you should find in the **log file** (eg. log/production.log). 

Screen shot would be also helpful.

## Expected Results
To have it like in the wiki, where I can choose Issue Template.

## Actual Results
![image](https://user-images.githubusercontent.com/29776703/85992139-c070d400-b9f4-11ea-9009-72841b696555.png)

Thanks!

**Comment by akiko-pusu** [comment]
Hi, @olegblecher 
Thanks for your environmental information!
Could you please give me the version of Issue Template pugin?
If v1.0.3, the situation is the same to #356

**Comment by akiko-pusu** [comment]
@olegblecher 
Could you please confirm the place you installed my plugin.
And plugin's directory name should be "redmine_issue_templates".
If not, a 404 error or migration error will happen.

See: https://github.com/akiko-pusu/redmine_issue_templates#plugin-installation

In addition to this, please confirm the permission of $YOUR_REDMINE_ROOT/public/plugin_assets/. 
JavaScripts or CSS file are stored under the directory when starting the Remine process.

**Comment by olegblecher** [comment]
Hi, I am using version 1.0.1 of the plugin. I actually also have the Checklists plugin installed! 

Here are the permissions of `plugin_assets`:

```
# ls -la /usr/share/redmine/public/plugin_assets
total 10
drwxr-xr-x 3 root root  4 Jun 16 10:40 .
drwxr-xr-x 8 root root 12 May  7 16:53 ..
-rw-r--r-- 1 root root  0 Dec 20  2019 empty
drwxr-xr-x 5 root root  5 Jun 16 10:40 redmine_crm
```

and this is where the plugin is installed (via git):

`/usr/share/redmine/plugins/redmine_issue_templates`

**Comment by olegblecher** [comment]
When I inspect in my webbrowser (Firefox) console, I get the following error:

`Loading failed for the <script> with source “https://tracker.website.se/plugin_assets/redmine_issue_templates/javascripts/issue_templates.js”.`

So I'm guessing something didn't get installed into plugin_assets..

**Comment by akiko-pusu** [comment]
It seems something wrong.

Did you run the setup task and migrations?

See: https://github.com/akiko-pusu/redmine_issue_templates#plugin-installation

1. Plugins should be stored under the plugins/ directory.
2. After starting the Redmine process, JavaScript files and Stylesheet files are located under ``public/plugin_assets`` directory automatically.

Here is my example of  ``public/plugin_assets`` directory.
If the Redmine checklists plugin is installed correctly, both  ``redmine_issue_templates`` and ``redmine_checklists`` directory are also generated.

Have you restarted Redmine's process (or Restarting your web server)?

```bash
plugin_assets $ tree . -L 1
.
├── empty
├── redmine_checklists
├── redmine_crm
└── redmine_issue_templates

plugin_assets $ tree -L 2 redmine_checklists/
redmine_checklists/
├── javascripts
│   └── checklists.js
└── stylesheets
    └── checklists.css

2 directories, 2 files
plugin_assets $ tree -L 2 redmine_issue_templates/
redmine_issue_templates/
├── images
│   ├── eraser.png
│   ├── issue_templates.png
│   ├── lamp.png
│   ├── preview.png
│   ├── reorder.png
│   └── ticket.png
├── javascripts
│   ├── fetch.umd.js
│   ├── issue_template_vue.js
│   ├── issue_templates.js
│   ├── issue_templates_es5.js
│   ├── node_modules
│   ├── package-lock.json
│   ├── polyfill.min.js
│   ├── template_checklists.js
│   ├── template_fields.js
│   ├── template_fields_es5.js
│   └── vue.min.js
└── stylesheets
    └── issue_templates.css

4 directories, 17 files
```

**Comment by olegblecher** [comment]
Hi,

I did. I've run the installation, restarted Apache, restarted the whole server aswell.

It seems like the installation is incomplete, but without errors?

In MySQL:

```
select * from schema_migrations where version like '%redmine_issue_templates%';
+----------------------------------------+
| version                                |
+----------------------------------------+
| 1-redmine_issue_templates              |
| 2-redmine_issue_templates              |
| 20121208150810-redmine_issue_templates |
| 20130630141710-redmine_issue_templates |
| 20130701024625-redmine_issue_templates |
| 2014020191500-redmine_issue_templates  |
| 20140307024626-redmine_issue_templates |
| 20140312054531-redmine_issue_templates |
| 20140330155030-redmine_issue_templates |
| 20160727222420-redmine_issue_templates |
| 20160828190000-redmine_issue_templates |
| 20160829001500-redmine_issue_templates |
| 20160829001530-redmine_issue_templates |
| 20170317082100-redmine_issue_templates |
| 20181104065200-redmine_issue_templates |
| 20190303082102-redmine_issue_templates |
| 20190714171020-redmine_issue_templates |
| 20190714211530-redmine_issue_templates |
| 20200101204020-redmine_issue_templates |
| 20200101204220-redmine_issue_templates |
| 20200102204815-redmine_issue_templates |
| 20200102205044-redmine_issue_templates |
| 20200103213630-redmine_issue_templates |
| 20200115073600-redmine_issue_templates |
| 20200314132500-redmine_issue_templates |
| 3-redmine_issue_templates              |
| 4-redmine_issue_templates              |
+----------------------------------------+
27 rows in set (0.00 sec)
```

```
mysql> show tables;
+-------------------------------------+
| Tables_in_redmine                   |
+-------------------------------------+
| ar_internal_metadata                |
| attachments                         |
| auth_sources                        |
| boards                              |
| changes                             |
| changeset_parents                   |
| changesets                          |
| changesets_issues                   |
| checklist_template_categories       |
| checklist_templates                 |
| checklists                          |
| comments                            |
| custom_field_enumerations           |
| custom_fields                       |
| custom_fields_projects              |
| custom_fields_roles                 |
| custom_fields_trackers              |
| custom_values                       |
| documents                           |
| email_addresses                     |
| enabled_modules                     |
| enumerations                        |
| global_issue_templates              |
| global_issue_templates_projects     |
| groups_users                        |
| import_items                        |
| imports                             |
| issue_categories                    |
| issue_relations                     |
| issue_statuses                      |
| issue_template_settings             |
| issue_templates                     |
| issues                              |
| journal_details                     |
| journals                            |
| member_roles                        |
| members                             |
| messages                            |
| news                                |
| note_templates                      |
| note_visible_roles                  |
| open_id_authentication_associations |
| open_id_authentication_nonces       |
| projects                            |
| projects_trackers                   |
| queries                             |
| queries_roles                       |
| repositories                        |
| roles                               |
| roles_managed_roles                 |
| schema_migrations                   |
| settings                            |
| time_entries                        |
| tokens                              |
| trackers                            |
| user_preferences                    |
| users                               |
| versions                            |
| watchers                            |
| wiki_content_versions               |
| wiki_contents                       |
| wiki_pages                          |
| wiki_redirects                      |
| wikis                               |
| workflows                           |
+-------------------------------------+
```

So I tried to uninstall it and then reinstall it:

````
rails  redmine:plugins:migrate NAME=redmine_issue_templates RAILS_ENV=production
== 1 CreateIssueTemplates: migrating ==========================================
-- create_table(:issue_templates, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 1.7996s
-- add_index(:issue_templates, :author_id)
   -> 3.8149s
-- add_index(:issue_templates, :project_id)
   -> 3.2449s
-- add_index(:issue_templates, :tracker_id)
   -> 4.0085s
== 1 CreateIssueTemplates: migrated (12.8685s) ================================

== 2 CreateIssueTemplateSettings: migrating ===================================
-- create_table(:issue_template_settings, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 2.8689s
== 2 CreateIssueTemplateSettings: migrated (2.8691s) ==========================

== 3 AddIssueTitleToIssueTemplates: migrating =================================
-- add_column(:issue_templates, :issue_title, :string, {})
   -> 3.1455s
== 3 AddIssueTitleToIssueTemplates: migrated (3.1640s) ========================

== 4 AddPositionToIssueTemplates: migrating ===================================
-- add_column(:issue_templates, :position, :integer, {:default=>1})
   -> 1.6130s
-- Update each template to set default position.
   -> 0.0068s
== 4 AddPositionToIssueTemplates: migrated (1.6205s) ==========================

== 2014020191500 AddShouldReplacedToIssueTemplateSettings: migrating ==========
-- add_column(:issue_template_settings, :should_replaced, :boolean, {:default=>false})
   -> 1.9614s
== 2014020191500 AddShouldReplacedToIssueTemplateSettings: migrated (1.9615s) =

== 20121208150810 AddIsDefaultToIssueTemplates: migrating =====================
-- add_column(:issue_templates, :is_default, :boolean, {:default=>false})
   -> 2.0135s
== 20121208150810 AddIsDefaultToIssueTemplates: migrated (2.0137s) ============

== 20130630141710 AddEnabledSharingToIssueTemplates: migrating ================
-- add_column(:issue_templates, :enabled_sharing, :boolean, {:default=>false})
   -> 1.5847s
== 20130630141710 AddEnabledSharingToIssueTemplates: migrated (1.5848s) =======

== 20130701024625 AddInheritTemplatesToIssueTemplateSettings: migrating =======
-- add_column(:issue_template_settings, :inherit_templates, :boolean, {:default=>false, :null=>false})
   -> 1.0398s
== 20130701024625 AddInheritTemplatesToIssueTemplateSettings: migrated (1.0399s)

== 20140307024626 CreateGlobalIssueTemplates: migrating =======================
-- create_table(:global_issue_templates, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 1.1682s
-- add_index(:global_issue_templates, :author_id)
   -> 5.8952s
-- add_index(:global_issue_templates, :tracker_id)
   -> 3.1039s
== 20140307024626 CreateGlobalIssueTemplates: migrated (10.1678s) =============

== 20140312054531 CreateGlobalIssueTemplatesProjects: migrating ===============
-- create_table(:global_issue_templates_projects, {:options=>"ENGINE=InnoDB", :id=>false})
   -> 6.0069s
== 20140312054531 CreateGlobalIssueTemplatesProjects: migrated (6.0071s) ======

== 20140330155030 RemoveIsDefaultFromGlobalIssueTemplates: migrating ==========
-- remove_column(:global_issue_templates, :is_default)
   -> 9.1785s
== 20140330155030 RemoveIsDefaultFromGlobalIssueTemplates: migrated (9.1786s) =

== 20160727222420 AddChecklistJsonToIssueTemplates: migrating =================
-- add_column(:issue_templates, :checklist_json, :text, {})
   -> 3.2108s
== 20160727222420 AddChecklistJsonToIssueTemplates: migrated (3.2110s) ========

== 20160828190000 AddChecklistJsonToGlobalIssueTemplates: migrating ===========
-- add_column(:global_issue_templates, :checklist_json, :text, {})
   -> 2.8665s
== 20160828190000 AddChecklistJsonToGlobalIssueTemplates: migrated (2.8666s) ==

== 20160829001500 ChangeIssueTemplateEnabledColumn: migrating =================
-- change_column(:issue_templates, :enabled, :boolean, {:default=>false, :null=>false})
   -> 7.6606s
== 20160829001500 ChangeIssueTemplateEnabledColumn: migrated (7.6607s) ========

== 20160829001530 ChangeGlobalIssueTemplateEnabledColumn: migrating ===========
-- change_column(:global_issue_templates, :enabled, :boolean, {:default=>false, :null=>false})
   -> 3.7685s
== 20160829001530 ChangeGlobalIssueTemplateEnabledColumn: migrated (3.7686s) ==

== 20170317082100 AddIsDefaultToGlobalIssueTemplates: migrating ===============
-- add_column(:global_issue_templates, :is_default, :boolean, {:default=>false, :null=>false})
   -> 4.4493s
== 20170317082100 AddIsDefaultToGlobalIssueTemplates: migrated (4.4494s) ======

== 20181104065200 AddUniqueKeyToGlobalIssueTemplatesProjects: migrating =======
-- add_index(:global_issue_templates_projects, [:project_id, :global_issue_template_id], {:unique=>true, :name=>"projects_global_issue_templates"})
   -> 3.1480s
== 20181104065200 AddUniqueKeyToGlobalIssueTemplatesProjects: migrated (3.1481s)

== 20190303082102 CreateNoteTemplates: migrating ==============================
-- create_table(:note_templates, {:options=>"ENGINE=InnoDB"})
   -> 4.8328s
-- add_index(:note_templates, :author_id)
   -> 1.3288s
-- add_index(:note_templates, :project_id)
   -> 2.0093s
-- add_index(:note_templates, :tracker_id)
   -> 6.5358s
-- add_index(:note_templates, :enabled)
   -> 4.1051s
== 20190303082102 CreateNoteTemplates: migrated (18.8125s) ====================

== 20190714171020 CreateNoteVisibleRoles: migrating ===========================
-- create_table(:note_visible_roles, {:options=>"ENGINE=InnoDB"})
   -> 6.4345s
-- add_index(:note_visible_roles, :note_template_id)
   -> 1.7418s
-- add_index(:note_visible_roles, :role_id)
   -> 2.4744s
== 20190714171020 CreateNoteVisibleRoles: migrated (10.6511s) =================

== 20190714211530 AddVisibilityToNoteTemplates: migrating =====================
-- add_column(:note_templates, :visibility, :integer, {:default=>2})
   -> 6.0223s
== 20190714211530 AddVisibilityToNoteTemplates: migrated (6.0224s) ============

== 20200101204020 AddRelatedLinkToIssueTemplates: migrating ===================
-- add_column(:issue_templates, :related_link, :text)
   -> 6.7095s
== 20200101204020 AddRelatedLinkToIssueTemplates: migrated (6.7097s) ==========

== 20200101204220 AddRelatedLinkToGlobalIssueTemplates: migrating =============
-- add_column(:global_issue_templates, :related_link, :text)
   -> 1.8535s
== 20200101204220 AddRelatedLinkToGlobalIssueTemplates: migrated (1.8537s) ====

== 20200102204815 AddLinkTitleToIssueTemplates: migrating =====================
-- add_column(:issue_templates, :link_title, :text)
   -> 4.3044s
== 20200102204815 AddLinkTitleToIssueTemplates: migrated (4.3045s) ============

== 20200102205044 AddLinkTitleToGlobalIssueTemplates: migrating ===============
-- add_column(:global_issue_templates, :link_title, :text)
   -> 2.9631s
== 20200102205044 AddLinkTitleToGlobalIssueTemplates: migrated (2.9633s) ======

== 20200103213630 AddBuiltinFieldsJsonToIssueTemplates: migrating =============
-- add_column(:issue_templates, :builtin_fields_json, :text)
   -> 2.1996s
== 20200103213630 AddBuiltinFieldsJsonToIssueTemplates: migrated (2.1997s) ====

== 20200115073600 AddBuiltinFieldsJsonToGlobalIssueTemplates: migrating =======
-- add_column(:global_issue_templates, :builtin_fields_json, :text)
   -> 2.5618s
== 20200115073600 AddBuiltinFieldsJsonToGlobalIssueTemplates: migrated (2.5619s)

== 20200314132500 ChangeColumnNoteTemplateDescription: migrating ==============
-- change_column(:note_templates, :description, :text)
   -> 9.8167s
== 20200314132500 ChangeColumnNoteTemplateDescription: migrated (9.8168s) =====
```

Everything still looks the same. Maybe I should copy the assets manually?

**Comment by akiko-pusu** [comment]
Hi, @olegblecher 
Let me confirm, are you new for setting up the Redmine and webserver?

I think this is not a bug and it's due to your installation steps.
Maybe you should confirm your plugin directory's permission, the user to run the apache web server,  and Apache configuration. (Exp. Apache might be run by the www-data user)

If you referred to some site for setting up Redmine, please confirm the steps again.
Redmine 's wiki pages about "How to install Redmine" would be your help.

- https://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_30x_on_Ubuntu_1404_with_Apache2_Phusion_Passenger_MySQL_Subversion_and_Git_(Gitolite)
- https://www.redmine.org/projects/redmine/wiki/HowTos

That's all information I could provide you.

**Comment by olegblecher** [comment]
Hi there, 
I've been working with Redmine for a couple of years now, and have carried out migrations myself.

I'm running Redmine from apt packages for Ubuntu, so everything is run by `root`.

I've managed to fix this by manually copying the Javascript/CSS and image files from`/usr/share/redmine/plugins/redmine_issue_templates/assets` to `/usr/share/redmine/public/plugin_assets/redmine_issue_templates`.

Now it works. The plugin installation does not put the files there.

**Comment by akiko-pusu** [comment]
> from apt packages for Ubuntu, so everything is run by root.

I think this is related to the permission.
Please check your "plugin assets directory" is writable by Apache user. (Normally nobody, www-data, apache user)

I hope this is any help.
https://stackoverflow.com/questions/57753672/redmine-plugin-assets-remains-empty

**Comment by olegblecher** [comment]
@akiko-pusu Thank you, this thread had the best solution!

I ran `ln -s /var/cache/redmine/default/plugin_assets /usr/share/redmine/public`

and now everything works as it should!!

Thank you for taking your time to help!

**Comment by akiko-pusu** [comment]
Great! This kind of operational information is quite useful for Redmine administrators.
Thanks again, and stay safe.
